### ISSUE TITLE
Plan PRO+

### ISSUE THREAD

**Issue by jpguay1234** [pablouser1/WuolahExtra#1]
Resulta que hay documentos que son muy grandes y requieren de un plan superior, llamado PRO+. El plan PRO funciona pero no el superior. 

Musha grasia

**Comment by pablouser1** [comment]
Hola, puedes pasarme un enlace con alguno de esos documentos? He estado buscando y no he encontrado ninguno

**Comment by Ardili13** [comment]
Hola,

Por ponerte un ejemplo: https://wuolah.com/apuntes/tecnologia-electrica/ejercicios-curso-20212022-te-t6boletin-pdf-6632976?utm_source=wuolah&utm_medium=referral&utm_campaign=file-openfile  
En estos ejercicios, el tamaño es superior a 50MB y no deja descargarlo ni verlo, sin tener el plan PRO+

**Comment by jpguay1234** [comment]
https://www.wuolah.com/apuntes/metodos-matematicos/apuntes-de-todo-pdf-6833927?utm_source=wuolah&utm_medium=referral&utm_campaign=file-sharefile&referral=jgu345 Este tambien es otro ejemplo

**Comment by pablouser1** [comment]
Hola, he estado investigando sobre esto y, al menos por ahora, no veo posible implementar esto.

Todas las comprobaciones que hace Wuolah para ver si tienes PRO+ se hacen de lado del servidor.
Este userscript se beneficia solo de modificar el comportamiento del cliente y no puede modificar lo que hace el servidor.
