### ISSUE TITLE
¿Archivos pesados?

### ISSUE THREAD

**Issue by Kadizta98** [pablouser1/WuolahExtra#16]
!!! Antes de empezar !!!:
- Asegúrate que estás en la útlima versión disponible de WuolahExtra
- Comprueba que tu problema no se haya informado anteriormente

**Setup**
Nombre y versión del navegador (Ej: Firefox 122, Chrome 100): **124.0.6367.209 (Build oficial) (arm64)**
Nombre y versión del userscript (Ej: ViolentMonkey 2.18.0, Tampermonkey 5.0.1): **ViolentMonkey 2.19.0**
Método de limpieza usado, si es necesario: (Ej: gulag, pdflib...): 

**Describe el fallo**
No entiendo mucho de esto, por lo que no se si habrá solución, pero a la hora de intentar descargar archivos con mucho peso, no me deja, indicando "debe registrarte como PRO+" , no se si hay alguna forma de saltarse este paso. 

Saludos y gracias por el trabajazo!

**Comment by pablouser1** [comment]
Duplicado de #12

En mi respuesta de esa issue puedes ver el estado de los archivos de PRO+
