### ISSUE TITLE
Los PDFs salen mal recortados

### ISSUE THREAD

**Issue by kikitor918** [pablouser1/WuolahExtra#24]
Pues eso, últimamente salen los pdfs mal recortados, incluso a veces salen corruptos y no los deja abrir. Será fallo de gulag cleaner pero lo comento por aquí también por si se puede hacer algo. 

pd: muchas gracias por lo que hacéis!

**Comment by pablouser1** [comment]
En efecto, tiene que ver con GulagCleaner (YM162/gulagcleaner#27)

Dejo la issue abierta hasta que esté arreglado.

**Comment by pablouser1** [comment]
Debería de estar ya arreglado, cierro la issue.
