### ISSUE TITLE
Abre una pestaña Blob al intentar descargar

### ISSUE THREAD

**Issue by Joselu25** [pablouser1/WuolahExtra#3]
Buenas, en las ultimas semanas al intentar descargar documentos desde el portatil(las carpetas las descarga bien y en la torre no tengo problema no se por que) se me abre automaticamente una pestaña de blob y no me descarga nada. ¿Me falta instalar algo nuevo o algo que cambiar para solucionarlo? Porque antes me iba perfecto y tambien he probado a usar otros navegadores (chrome y opera) y en ambos me da el mismo problema

**Comment by pablouser1** [comment]
Hola, comprueba la versión de WuolahExtra que estás usando tanto en tu portatil como en tu torre y asegurate de usar la última versión.

Si ya estás en la v1.3.1 y sigues teniendo ese problema puede ser por el manager de userscripts que usas (Tampermonkey, ViolentMonkey...)

Comprueba cual estás usando junto con la versión y coméntamelo, en la versión v1.3.1 se ha implementado la API moderna y quizás te está dando problemas.

**Comment by gabevalbu** [comment]
Hola, a mi me pasa lo mismo. 
Tengo la última versión de violentmonkey

**Comment by pablouser1** [comment]
Hola, esto puede estar relacionado con YM162/gulagcleaner#14

En la configuración del userscript podéis elegir otro método de limpieza distinto a GulagCleaner, "params" funciona bien por ahora

**Comment by pablouser1** [comment]
@Joselu25 cuando puedas verifica que esto arregla el problema

**Comment by Joselu25** [comment]
Efectivamente eso va perfecto, muchas gracias man

**Comment by pablouser1** [comment]
Perfecto, cierro la issue entonces.
Voy a fijar la issue para la gente que llegue con este mismo problema.

**Comment by pablouser1** [comment]
Con la nueva versión 1.4.1 se actualiza a la última versión de GulagCleaner (0.12.2) que arregla definitivamente el problema

**Comment by JoseRamonCarmonaOrtega** [comment]
a mí me está pasando este mismo problema, y estoy en esta ultima versión. ¿Tengo que hacer algo especial para usar la ultima version de gulagcleaner?
