### ISSUE TITLE
No deja descargar carpetas

### ISSUE THREAD

**Issue by gabevalbu** [pablouser1/WuolahExtra#4]
Buenas, no me deja descargar carpetas enteras, pero si los documentos individuales. 
Me salta el recaptcha, pero al rellenarlo no se descarga la carpeta.
He probado desactivando todas las extensiones que tengo.
Estoy en firefox con todas las versiones mas nuevas.
Muchas gracias

**Comment by pablouser1** [comment]
Wuolah está cambiando bastante como funciona su plataforma y ahora esta función hace el zip de lado del servidor y no del cliente como antes, asi que ya hay una comprobación real de si eres pro o no.

Si abres las herramientas de desarrollador y vas a consola deberías ver este error también:
![err](https://github.com/pablouser1/WuolahExtra/assets/17802865/90b43f47-b37b-4775-9ea8-168075d8ae42)

Esto tiene una solución pero requiere de algo de tiempo (extender el userscript para que él mismo cree el zip a partir de los archivos de la carpeta)

**Comment by pablouser1** [comment]
@jobata220 Por ahora este problema no tiene una solución sencilla. Seria necesario un rato de investigación de cómo funciona Wuolah para incluir en el userscript una función que descargue individualmente todos los archivos de una carpeta y los fusione en un zip.
