### ISSUE TITLE
El PDF está dañado

### ISSUE THREAD

**Issue by irwinsqxxn** [pablouser1/WuolahExtra#5]
Cuando intento descargar cualquier tipo de archivo, al abrirlo me pone que está dañado. Tengo la última versión y lo he intentado en Microsoft Edge y Firefox. 
![imagen](https://github.com/pablouser1/WuolahExtra/assets/157165296/e5d20ac2-3e43-40e6-80c7-1a9c57f55dd9)

**Comment by pablouser1** [comment]
Duplicado de #3, abre los ajustes del userscript y cambia el método de limpiado a otro (params funciona bien por ahora)

**Comment by irwinsqxxn** [comment]
cómo lo puedo cambiar??

**Comment by pablouser1** [comment]
Puedes consultar la documentación de GreaseMonkey al respecto:
https://wiki.greasespot.net/Greasemonkey_Manual:Monkey_Menu#The_Menu

**Comment by irwinsqxxn** [comment]
Tengo que sustituir por "PARAMS" en todos los sitios que pone "GULAG" y "PDFLIB"? (en lo resaltado ya he puesto params en vez del metodo que habia pero al guardar da error)
![imagen](https://github.com/pablouser1/WuolahExtra/assets/157165296/cd85dd38-1ebb-4ee4-9880-fe8cecf70305)
