### ISSUE TITLE
No hace nada

### ISSUE THREAD

**Issue by SGMazinger** [pablouser1/WuolahExtra#6]
El programa en el Tampermonkey sale como activado, pero ni bloquea la publicidad de la página ni descarga documentos. Sí que cambia la versión de la página (no te pide esperar para descargar los documentos) pero al descargarse se abre una nueva página ("blob:https://wuolah.com/…") y no se descarga nada. Tampoco descarga carpetas.

**Comment by pablouser1** [comment]
Hola, la descarga de carpetas no funciona actualmente (#4).

Los documentos individuales sí que los puedo descargar usando v.1.4.2 con el método gulag. Ese blob debería de contener el archivo que solicitaste con la opción de descargarlo.

**Comment by SGMazinger** [comment]
> Hola, la descarga de carpetas no funciona actualmente (#4).
> 
> Los documentos individuales sí que los puedo descargar usando v.1.4.2 con el método gulag. Ese blob debería de contener el archivo que solicitaste con la opción de descargarlo.

¿Y cómo puedo descargar el pdf a través del blob?

**Comment by Ardili13** [comment]
@SGMazinger Has conseguido descargar ya a partir del blob?

**Comment by SGMazinger** [comment]
@Ardili13 Todavía no...

**Comment by pablouser1** [comment]
@SGMazinger puedes confirmar que #10 te arregla el problema?

**Comment by SGMazinger** [comment]
> @SGMazinger puedes confirmar que #10 te arregla el problema?

Lo he vuelto a probar con la v1.4.3 y ya funciona. No se abre un blob, directamente descarga el archivo. Gracias
