### ISSUE TITLE
El programa no responde

### ISSUE THREAD

**Issue by maariamaartin** [pablouser1/WuolahExtra#8]
Tras haberme descargado, eliminado e intentado de nuevo, no me deja descargar archivos del wuolah. Aunque la pagina si funciona y aparece la interfaz sin anuncios, cuando me quiero descargar un archivo me aparece una nueva pestaña con codigo que no comprendo. He de añadir que en ajustes he añadido el zip

**Comment by pablouser1** [comment]
Hola, ¿podrías hacer una captura de pantalla de ese código que te sale y publicarlo aquí?

**Comment by pablouser1** [comment]
@maariamaartin puedes confirmar que #10 te arregla el problema ?

**Comment by pablouser1** [comment]
Doy la issue por completada por inactividad.
